[package]
name = "quick-commit"
description = "Commit changes quickly"
version = "0.2.4"
edition = "2021"
repository = "https://github.com/thomas-forbes/quick-commit"
license = "MIT"
readme = "README.md"
keywords = ["cli", "git"]
authors = ["Thomas Forbes <34174315+thomas-forbes@users.noreply.github.com>"]
categories = ["command-line-utilities"]
exclude = ["assets/*"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
git2 = "0.13.22"
colored = "2.0"
ureq = { version = "2", features = ["json"] }
serde_json = "1"
serde = { version = "1", features = ["derive"] }
toml = "0.8"
dirs = "6"
rustyline = "17.0.2"

[[bin]]
name = "qc"
path = "src/main.rs"
